<?php

namespace FOS\FacebookBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FacebookController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FOS\FacebookBundle\Controller\FacebookController();
        return $instance;
    }
}
