imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:     ~ 
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    
# Doctrine Extensions Configuration
stof_doctrine_extensions:
      default_locale: en_US
      translation_fallback: true
      orm:
          default:
            sluggable: true
            timestampable: true
            tree: false
            translatable: true
            loggable: false

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'A2lixTranslationFormBundle::form.html.twig'
    globals:
        languages: %languages%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [MYMainBundle, MYUserBundle, FOSUserBundle, TwigBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        # jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
# sonata
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
          
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        # role security information
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            OPERATOR: OPERATOR
            MASTER: MASTER
            
    title:      MyNet.am
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list } 

            # Customize this part to add new block configuration
            #- { position: right, type: sonata.block.service.text, settings: { content: "<h3>Cron</h3> Cron jobs can be found at <a href='/admin/cron-manager/' >Cron Manager</a>" } }
            
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: public
    user_class: MY\UserBundle\Entity\User
    group:
        group_class:  MY\UserBundle\Entity\Group
    profile:
        form:
            type:               fos_user_profile
            name:               fos_user_profile_form
            validation_groups:  [Profile]
    change_password:
        form:
            type:               fos_user_change_password
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword]
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address:        ...
                sender_name:    ...
            template:   FOSUserBundle:Resetting:email.txt.twig
        form:
            type:               fos_user_resetting
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword]
    
sonata_user:
    security_acl:     false
    impersonating_route:    sonata_admin_dashboard
    class:
        user:         MY\UserBundle\Entity\User
        group:        MY\UserBundle\Entity\Group

sonata_media:
    default_context: default
    class:
        media:              MY\MediaBundle\Entity\Media
        gallery:            MY\MediaBundle\Entity\Gallery
        gallery_has_media:  MY\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb
    contexts:
        default: # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                list: { width: 200 , quality: 70}
                homepage: { width: 225 , quality: 70}
                lightbox: { width: 700 , quality: 70}
                
        news_gallery:
            providers:
                - sonata.media.provider.image

            formats:
                list: { width: 225 , quality: 70}
                home: { width: 107 , quality: 70}
                
        slider:
            providers:
                - sonata.media.provider.image

            formats:
                list: { width: 580 , quality: 70} 
          
        ads:
            providers:
                - sonata.media.provider.image

            formats:
                right: { width: 180 , quality: 70}
                left: { width: 240 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    providers :
        file:
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'zip', 'rar']
            
    filesystem:
        local:
            directory: %kernel.root_dir%/../web/uploads/media
            create: false

a2lix_translation_form:
    locales: [en]                       # [Optionnal] Array of translations locales. Can be specified in the form. 
    default_required: false             # [Optionnal] Default to false. In this case, translation fields are not mark as required with html5

services:
    #acme_hello.twig.extension.debug:
    #    class:        Twig_Extension_Debug
    #    tags:
    #         - { name: 'twig.extension' }
    #my.ads.twig.ads_extension:
    #    class: MY\AdsBundle\Twig\Extension\AdsExtension
    #    tags:
    #         - { name: 'twig.extension' }
    #    arguments: [ @doctrine.orm.entity_manager ]

#paginatin
knp_paginator:
    page_range: 5 # default page range used in pagination control
    default_options:
        page_name: page # page query parameter name
        sort_field_name: sort # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

parameters:
    items_per_page: 10
    languages: 
      en: ENG

stfalcon_tinymce:
    #textarea_class: "tinymce"
    language: en

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source']
    filebrowser_upload_url:
        url: /upload/
        
########################
#fos_facebook:
  #  file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
   # alias:  facebook
   # app_id: %fos_facebook_app_id%
   # secret: %fos_facebook_secret%
   # cookie: true
   # permissions: [email, user_birthday, user_location]
