<?php

namespace EnhancedProxy800d6335_53dec1f9d041c19ebe90100ea45ce8ac4e4975c7\__CG__\MY\MainBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PageTreeSortController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/mynet/app/cache/dev/jms_diextra/proxies/EnhancedProxy800d6335_53dec1f9d041c19ebe90100ea45ce8ac4e4975c7-__CG__-MY-MainBundle-Controller-PageTreeSortController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('MY\\MainBundle\\Controller\\PageTreeSortController' => array('upAction' => array(0 => 'security.access.method_interceptor'), 'downAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy800d6335_df27d8f2433f68f08f1714f26156edc8403699ae\__CG__\MY\MainBundle\Controller\PageTreeSortController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
