<?php

namespace Proxies\__CG__\MY\MainBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Suggestion extends \MY\MainBundle\Entity\Suggestion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function preUpload()
    {
        $this->__load();
        return parent::preUpload();
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function addTranslation(\MY\MainBundle\Entity\SuggestionTranslation $translation)
    {
        $this->__load();
        return parent::addTranslation($translation);
    }

    public function removeTranslation(\MY\MainBundle\Entity\SuggestionTranslation $translations)
    {
        $this->__load();
        return parent::removeTranslation($translations);
    }

    public function getTranslations()
    {
        $this->__load();
        return parent::getTranslations();
    }

    public function setTitleList($titleList)
    {
        $this->__load();
        return parent::setTitleList($titleList);
    }

    public function getShowApplication()
    {
        $this->__load();
        return parent::getShowApplication();
    }

    public function setShowApplication($show_application)
    {
        $this->__load();
        return parent::setShowApplication($show_application);
    }

    public function getShowContact()
    {
        $this->__load();
        return parent::getShowContact();
    }

    public function setShowContact($show_contact)
    {
        $this->__load();
        return parent::setShowContact($show_contact);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setTitleRaw($titleRaw)
    {
        $this->__load();
        return parent::setTitleRaw($titleRaw);
    }

    public function getTitleRaw()
    {
        $this->__load();
        return parent::getTitleRaw();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function getTitleList()
    {
        $this->__load();
        return parent::getTitleList();
    }

    public function setSuggestionRaw($suggestionRaw)
    {
        $this->__load();
        return parent::setSuggestionRaw($suggestionRaw);
    }

    public function getSuggestionRaw()
    {
        $this->__load();
        return parent::getSuggestionRaw();
    }

    public function setIntro($intro)
    {
        $this->__load();
        return parent::setIntro($intro);
    }

    public function getIntro()
    {
        $this->__load();
        return parent::getIntro();
    }

    public function setSuggestion($suggestion)
    {
        $this->__load();
        return parent::setSuggestion($suggestion);
    }

    public function getSuggestion()
    {
        $this->__load();
        return parent::getSuggestion();
    }

    public function setSolutionRaw($solutionRaw)
    {
        $this->__load();
        return parent::setSolutionRaw($solutionRaw);
    }

    public function getSolutionRaw()
    {
        $this->__load();
        return parent::getSolutionRaw();
    }

    public function setSolution($solution)
    {
        $this->__load();
        return parent::setSolution($solution);
    }

    public function getSolution()
    {
        $this->__load();
        return parent::getSolution();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setInHomepage($inHomepage)
    {
        $this->__load();
        return parent::setInHomepage($inHomepage);
    }

    public function getInHomepage()
    {
        $this->__load();
        return parent::getInHomepage();
    }

    public function setCorrectedEn($corrected_en)
    {
        $this->__load();
        return parent::setCorrectedEn($corrected_en);
    }

    public function getCorrectedEn()
    {
        $this->__load();
        return parent::getCorrectedEn();
    }

    public function setInTop($inTop)
    {
        $this->__load();
        return parent::setInTop($inTop);
    }

    public function getInTop()
    {
        $this->__load();
        return parent::getInTop();
    }

    public function setInDiscussion($inDiscussion)
    {
        $this->__load();
        return parent::setInDiscussion($inDiscussion);
    }

    public function getInDiscussion()
    {
        $this->__load();
        return parent::getInDiscussion();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setUser(\MY\UserBundle\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setImage(\MY\MediaBundle\Entity\Media $image = NULL)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function setImageSlide(\MY\MediaBundle\Entity\Media $imageSlide = NULL)
    {
        $this->__load();
        return parent::setImageSlide($imageSlide);
    }

    public function getImageSlide()
    {
        $this->__load();
        return parent::getImageSlide();
    }

    public function setPath($path)
    {
        $this->__load();
        return parent::setPath($path);
    }

    public function getPath()
    {
        $this->__load();
        return parent::getPath();
    }

    public function setFile($file)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function setArchive($archive)
    {
        $this->__load();
        return parent::setArchive($archive);
    }

    public function getArchive()
    {
        $this->__load();
        return parent::getArchive();
    }

    public function setEdited($edited)
    {
        $this->__load();
        return parent::setEdited($edited);
    }

    public function getEdited()
    {
        $this->__load();
        return parent::getEdited();
    }

    public function setTranslated($translated)
    {
        $this->__load();
        return parent::setTranslated($translated);
    }

    public function getTranslated()
    {
        $this->__load();
        return parent::getTranslated();
    }

    public function setCorrected($corrected)
    {
        $this->__load();
        return parent::setCorrected($corrected);
    }

    public function getCorrected()
    {
        $this->__load();
        return parent::getCorrected();
    }

    public function setUserUploaded($user_uploaded)
    {
        $this->__load();
        return parent::setUserUploaded($user_uploaded);
    }

    public function getUserUploaded()
    {
        $this->__load();
        return parent::getUserUploaded();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setLikes($likes)
    {
        $this->__load();
        return parent::setLikes($likes);
    }

    public function getLikes()
    {
        $this->__load();
        return parent::getLikes();
    }

    public function setMetaTitle($metaTitle)
    {
        $this->__load();
        return parent::setMetaTitle($metaTitle);
    }

    public function getMetaTitle()
    {
        $this->__load();
        return parent::getMetaTitle();
    }

    public function setMetaDesc($metaDesc)
    {
        $this->__load();
        return parent::setMetaDesc($metaDesc);
    }

    public function getMetaDesc()
    {
        $this->__load();
        return parent::getMetaDesc();
    }

    public function setMetaKw($metaKw)
    {
        $this->__load();
        return parent::setMetaKw($metaKw);
    }

    public function getMetaKw()
    {
        $this->__load();
        return parent::getMetaKw();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'updated', 'slug', 'name', 'title_raw', 'title', 'title_list', 'suggestion_raw', 'intro', 'suggestion', 'solution_raw', 'solution', 'created_at', 'status', 'in_homepage', 'archive', 'in_top', 'in_discussion', 'position', 'show_contact', 'show_application', 'likes', 'edited', 'translated', 'corrected', 'user_uploaded', 'path', 'meta_title', 'meta_desc', 'meta_kw', 'user', 'image', 'image_slide', 'translations');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}