<?php

namespace MY\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
  /**
   * 
   * @return type
   */
  public function findOneByHomepageOrderedById()
  {
    $query = $this->getEntityManager()
                    ->createQuery("SELECT m.providerMetadata FROM MYMediaBundle:Media m 
                           WHERE m.in_homepage = 1
                           ORDER BY m.id DESC");
    $query->setMaxResults(1);

    return $query->getResult();
  }
}
