<?php

namespace MY\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{

  public function findAllByType($type)
  {

    switch ($type)
    {
      case'photos':
        $typeID = 1;
        break;
      case'videos':
        $typeID = 2;
        break;
      default:
        throw $this->createNotFoundException('Page not found!');
    }

    $query = $this->getEntityManager()
            ->createQuery('SELECT g FROM MYMainBundle:Gallery g
			WHERE g.type = ' . intval($typeID));

    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }

  public function findBySlug($slug)
  {

    $query = $this->getEntityManager()
            ->createQuery('SELECT g FROM MYMainBundle:Gallery g
			WHERE g.slug = \'' . $slug . '\'');

    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }

}
