<?php

namespace MY\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestingsRepository extends EntityRepository
{

  public function findAllMens()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:Interestings n WHERE n.status=1 and n.type=1 ORDER BY n._date DESC');


    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }

  public function findAllWomens()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:Interestings n WHERE n.status=1 and n.type=2 ORDER BY n._date DESC');


    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }
  
  public function findAllKids()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:Interestings n WHERE n.status=1 and n.type=3 ORDER BY n._date DESC');


    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }
  
  public function findOneBySlug($slug)
  {
    $em = $this->getEntityManager();
    $res = $em->createQuery("SELECT n FROM MYMainBundle:Interestings n WHERE n.slug = :slug");
    $res->setParameters(array('slug' => $slug));
    //$res->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $res->getResult();
  }

  public function findAllInterestingsArchive()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:Interestings n WHERE n._date < \'2013-01-01\' ORDER BY n._date DESC');
    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }

  public function findAllHomepageInterestings()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:Interestings n WHERE n.homepage_status = 1
			ORDER BY n.created DESC');
    $query->setMaxResults(10);
    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }
  
  
  
}