<?php

namespace MY\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

  public function findAllNews()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:News n WHERE n.news_date > \'2013-01-01\' ORDER BY n.news_date DESC');


    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }

  public function findOneBySlug($slug)
  {
    $em = $this->getEntityManager();
    $res = $em->createQuery("SELECT n FROM MYMainBundle:News n WHERE n.slug = :slug");

    $res->setParameters(array('slug' => $slug));
    //$res->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $res->getResult();
  }

  public function findAllNewsArchive()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:News n WHERE n.news_date < \'2013-01-01\' ORDER BY n.news_date DESC');


    //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }

  public function findAllHomepageNews()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM MYMainBundle:News n WHERE n.homepage_status = 1
			ORDER BY n.created DESC');
    $query->setMaxResults(10);
   // $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

    return $query->getResult();
  }
  
  
  
}