<?php

namespace MY\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * Slider Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
  public function findAll()
  {
    $query = $this->getEntityManager()
            ->createQuery('SELECT s FROM MYMainBundle:Slider s ORDER BY s.id DESC');

   return $query->getResult();
  }
}
